### PR TITLE
Merge master to cd_dev

### PR DESCRIPTION
**Pull request by panaC**

### CODE REVIEW

**Comment by danielweck** [comment]
Great thanks! I wasn't sure when this would be safe. I assume you merged `master` into `cd` first? (as `cd_dev`  "extends" `cd`) ... checking now

**Comment by danielweck** [comment]
...ah no, `cd` is not up to date. Is that intentional? https://github.com/readium/readium-lcp-server/tree/cd

**Comment by danielweck** [comment]
...ok, so I guess `cd` is becoming obsolete now? (`cd_dev` becomes the new EDRLab deployment?)
https://github.com/readium/readium-lcp-server/commit/2c3acd36761aad80c95f17fc4c22474a04912a56

I personally use `cd_dev` for my local "dev" testing, as the name implies. Just a nice Docker setup that makes my life easy :)

**Comment by panaC** [comment]
`cd` is obsolete now
https://front-prod.edrlab.org is deployed on lcpv2 now

**Pull request merged**
