### PR TITLE
Isolate userkey generation

### PR DESCRIPTION
**Pull request by clebeaupin**
Make it easy to replace userkey generation

### CODE REVIEW

**Comment by jpbougie** [comment]
This is a good first step, but I would put it behind an interface to be able to swap it later.

Something like:
```go
type UserKeyGenerator interface {
  TransformClearKey(string) ([]byte, error)
  TransformHashedKey([]byte) ([]byte, error)
}
```

which will allow us to either start from the clear value or from the hashed passphrase, and be able to add some key stretching according to the profile (the default implementation being a no-op).

**Comment by clebeaupin** [comment]
+1

**Comment by llemeurfr** [comment]
re. @jpbougie "which will allow us to either start from the clear value or from the hashed passphrase"... we decided to start from the hashed passphrase only as soon as we can disregard the managed frontend UI. Hashing the passphrase should be the first think a uI does before sending the data to the userkey transform. There should be not clear passphrase exchange.

**Comment by danielweck** [comment]
all the details here:
https://github.com/readium/readium-lcp-server/issues/136
(lcp/manage/index.html, etc.)

**Pull request merged**
