### PR TITLE
Gorm db refactor

### PR DESCRIPTION
**Pull request by danielweck**
local "mirror" of existing remote PR:
https://github.com/readium/readium-lcp-server/pull/173/commits
https://github.com/badu/readium/commits/master

### CODE REVIEW

**Comment by danielweck** [comment]
FYI, I created this redundant PR using the following Git commands:
* `git clone git@github.com:readium/readium-lcp-server.git && cd readium-lcp-server`
* `git checkout develop`
* `git remote add badu https://github.com/badu/readium.git && git remote -v`
* `git fetch badu && git branch -av`
* `git checkout -b gorm-db-refactor badu/master && git branch -av`
* `git push origin gorm-db-refactor`
* Then open in web browser this URL https://github.com/readium/readium-lcp-server/pull/new/gorm-db-refactor to create this PR

**Comment by danielweck** [comment]
Note that unlike https://github.com/readium/readium-lcp-server/pull/173 (which targets `develop`), this PR targets `master`. It is important to note that both `develop` and `master` have since evolved, making both PRs invalid (i.e. code conflicts need resolving before merging).

The date of first "refactor" commit was April 25th 2018:
https://github.com/badu/readium/commit/c951447d5bc63fad3eaec6d4008ad97b34dc7b5a

...immediately after March 6th in `master`:
https://github.com/badu/readium/commit/52a3444f04521420539d4e7dbdd3546b8eb533b2

Since then, there has been ; at this time of writing ; 9 additional commits in `master` (which explain the conflicts):
https://github.com/readium/readium-lcp-server/commits/master

**Comment by danielweck** [comment]
* `git checkout gorm-db-refactor`
* `git merge master`

## Easy conflict to fix:

* `cmd/lcpencrypt/main.go`

`git diff README.md`
=>
License header change at top of file.

## Less easy conflict to fix:

* `README.md`

`git diff README.md`
=>
Beside the actual conflict, there are other changes which need to be carefully reviewed such as `lutserver` vs. `frontend`!

## Harder to fix:

(because "files deleted in `gorm-db-refactor`, but since then, modified in `master`")

* `lsdserver/api/license_status.go`
* `lcpserver/server/server.go`
* `frontend/webpublication/webpublication.go`
* `frontend/weblicense/weblicense.go`
* `frontend/server/server.go`
* `config/config.go`
* `api/common_server.go`

**Comment by danielweck** [comment]
`git diff README.md`
=>
```diff
diff --cc README.md
index 4813d654,504bdd20..00000000
--- a/README.md
+++ b/README.md
@@@ -126,11 -127,22 +127,22 @@@ The License Server, License Status Serv
  
  * READIUM_LCPSERVER_CONFIG for the LCP server
  * READIUM_LSDSERVER_CONFIG for the LSD server
 -* READIUM_FRONTEND_CONFIG for the frontend test server
 +* READIUM_FRONTEND_CONFIG for the lutserver test server
  
- The three servers may share the same configuration file (if they are both executed on the same server) or they may have their own configuration file. In the first case, the htpasswd file and database may also be shared.
+ The value of the three global variables will be on the form /<path>/lcpconfig.yaml.
+ 
+ The three servers may share the same configuration file (if they are both executed on the same server) or they may have their own configuration file. 
+ 
+ The LCP and LSD servers also require authenticated API requests for some of their functionalities. A password file name .htpasswd must therefore be created to handle such authentication data, for each module. Like the configuration file, the .htpasswd file may be shared between the two modules.
+ 
+ A source example for creating a password file is http://www.htaccesstools.com/htpasswd-generator/. 
+ The htpasswd file format is e.g.:
+ ```sh
+       User1:$apr1$OMWGq53X$Qf17b.ezwEM947Vrr/oTh0
+       User2:$apr1$lldfYQA5$8fVeTVyKsiPeqcBWrjBKMT
+ ```
  
- Here are details about all configuration properties:
+ Here are details about the configuration properties:
  
  *License Server*
  
@@@ -142,15 -154,10 +154,10 @@@
  - "host": the public server hostname, `hostname` by default
  - "port": the listening port, `8989` by default
  - "public_base_url": the public base URL, combination of the host and port values on http by default 
 -- "database": the URI formatted connection string to the database, `sqlite3://file:lcp.sqlite?cache=shared&mode=rwc` by default
 +- "database": the URI formatted connection string to the database, `sqlite3://file:lcp.sqlite?cache=shared&mode=rwc` by default. The URI starts with the database dialect (which can be sqlite3, mysql, postgres, mssql)
  - "auth_file": mandatory; the authentication file (an .htpasswd). Passwords must be encrypted using MD5.
  
- A source example for creating a password file is http://www.htaccesstools.com/htpasswd-generator/. 
- The htpasswd file format is e.g.:
- ```sh
-       User1:$apr1$OMWGq53X$Qf17b.ezwEM947Vrr/oTh0
-       User2:$apr1$lldfYQA5$8fVeTVyKsiPeqcBWrjBKMT
- ```
+ Note: It may be practical to put the authentication file in the configuration folder ("lcpconfig" in the samples below). 
  
  "storage" section: parameters related to the storage of encrypted publications. 
  - "filesystem" section: parameters related to a file system storage.
@@@ -266,13 -275,13 +277,21 @@@ lcp_update_auth
  - "host": the public server hostname, `hostname` by default
  - "port": the listening port, `8991` by default
  - "public_base_url": the public base URL, combination of the host and port values on http by default 
 -- "database": the URI formatted connection string to the database, `sqlite3://file:frontend.sqlite?cache=shared&mode=rwc` by default
 +- "database": the URI formatted connection string to the database, `sqlite3://file:frontend.sqlite?cache=shared&mode=rwc` by default. The URI starts with the database dialect (which can be sqlite3, mysql, postgres, mssql)
  - "master_repository": repository where the uploaded EPUB files are stored before encryption. 
++<<<<<<< HEAD
 +- "encrypted_repository": repository where the encrypted EPUB files are stored after upload.
 +- "directory": the directory containing the client app; by default $GOPATH/src/github.com/readium/readium-lcp-server/lutserver/manage.
 +- "provider_uri": provider uri, which will be inserted in all licenses produced via this test lutserver.
 +- "right_print": allowed number of printed pages, which will be inserted in all licenses produced via this test lutserver.
 +- "right_copy": allowed number of copied characters, which will be inserted in all licenses produced via this test lutserver.
++=======
+ - "encrypted_repository": repository where the encrypted EPUB files are stored after upload. The LCP server must have access to the path declared here; it will move each encrypted file to its storage folder on notification of encryption from the Frontend Server. 
+ - "directory": the directory containing the client app; by default $GOPATH/src/github.com/readium/readium-lcp-server/frontend/manage.
+ - "provider_uri": provider uri, which will be inserted in all licenses produced via this test frontend.
+ - "right_print": allowed number of printed pages, which will be inserted in all licenses produced via this test frontend.
+ - "right_copy": allowed number of copied characters, which will be inserted in all licenses produced via this test frontend.
++>>>>>>> master
  
  The config file of a Frontend Test Server must define a "lcp" "public_base_url", "lsd" "public_base_url", "lcp_update_auth" "username" and "password", and "lsd_notify_auth" "username" and "password".
  
@@@ -321,8 -330,11 +340,11 @@@ each server must be launched in a diffe
  Each server is executed with no parameter:
  - lcpserver
  - lsdserver
 -- frontend
 +- lutserver
  
+ After the frontend server is launched, you can access to the server GUI via its base url, e.g. http://http://127.0.0.1:8991
+ 
+ NOTE: even if you deploy the server locally, using 127.0.0.1 is not recommended, as you won't be able to access the modules from e.g. a mobile app. It's much better to use the WiFi IPv4 address to your computer, and access the server from your mobile device via WiFi.  
  
  Contributing
  ============
```

**Comment by danielweck** [comment]
Overview of all 9 commits in `master` since the branch was forked to start the refactoring:
https://github.com/readium/readium-lcp-server/compare/52a3444f04521420539d4e7dbdd3546b8eb533b2...master

This will help "cherry-picking" recent code changes from `master` in order to replicate them into the refactored branch (which was forked from an old `master` revision).

For example `api/common_server.go` does not exist at this location anymore:
https://github.com/readium/readium-lcp-server/compare/52a3444f04521420539d4e7dbdd3546b8eb533b2...master#diff-a2400034cc494921574abaccd0637176
...because in branch `gorm-db-refactor` this is where the HTTP `ContentType` "globals" are defined:
https://github.com/readium/readium-lcp-server/blob/86e480e3eb586f5d59de07634ec3434f83b15b97/lib/http/types.go#L66
( https://github.com/readium/readium-lcp-server/blob/gorm-db-refactor/lib/http/types.go#L66 )

etc.
(lots of work to cherry-pick, but not impossible :)

**Comment by danielweck** [comment]
Also note that `dbmodel/mysql db setup.sql` was changed to match the refactoring:
https://github.com/readium/readium-lcp-server/commit/c951447d5bc63fad3eaec6d4008ad97b34dc7b5a#diff-f037b9473016133a16b952546c864ab5

...but not `dbmodel/sqlite db setup.sql`:
https://github.com/readium/readium-lcp-server/blob/gorm-db-refactor/dbmodel/sqlite%20db%20setup.sql
and not `dbmodel/sqlite-evol-1.sql`:
https://github.com/readium/readium-lcp-server/blob/gorm-db-refactor/dbmodel/sqlite-evol-1.sql

**Comment by llemeurfr** [comment]
We're keeping this branch open for now in order to take parts of it for a v2 of the LCP server. But this will never be merged on master; too many modifications not fully validated.

**Comment by llemeurfr** [comment]
This is part of the major V2 rewrite (work on progress in the EDRLab Github space).

**Pull request closed without merging**
