### PR TITLE
Go Modules

### PR DESCRIPTION
**Pull request by tooolbox**
Modern dependency management in Go uses Go Modules.  This PR adds working `go.mod` and `go.sum` files.

To ensure everything worked correctly after the conversion, I used the command `go test ./...`

However, this failed for a variety of reasons.  It seems that the tests on `master` were not all working.  So all of the actual code changes you see in this PR were done to get the tests working, so that the Go Module conversion can be seen to work.

In some cases the decisions here were "quick and dirty" where the actual correct architecture or design choices are unclear.  A prime example is the database access; it seems that with adding MySQL, some conditions were added to database setup to check the db type in the config; this unfortunately seems to have broken the tests that depend on the database.  My solution of "set the configuration at the start of the test" is brittle and undesirable in the long run.

In spite of any quick-and-dirty fixes, all tests now pass and by enabling CI this can be kept in moving forward.

EDIT: CI could be enabled with something like this `.travis.yml`:
```yml
language: go
go:
  - 1.10.x
  - 1.11.x
  - 1.12.x
  - 1.13.x
env:
  - GO111MODULE=on
script: go get github.com/readium/readium-lcp-server && go test
notifications:
  email: false
```
After adding the file, you would then need to actually configure Travis to work with your repos. 
 (I'm not an expert, just cobbling together the data.)

### CODE REVIEW

**Comment by tooolbox** [comment]
If I need to open this against a branch other than Master, I can.

**Comment by tooolbox** [comment]
@llemeurfr are you interested in this?

**Comment by llemeurfr** [comment]
@tooolbox sure I am. I just solved some remaining issues on the MySQL support, will study your PR this week (I'm discovering go modules). 
 I'll solve the conflict on license_statuses.go, I see your point about tests which fail because of database differences (I hope the modification I applied to several requests are solving that). 

Can you please redirect the PR to the develop branch?
Thanks a lot.

**Comment by tooolbox** [comment]
Okay great, I changed to merge to the `develop` branch.  As you say, there is now a conflict in `license_statuses/license_statuses.go` which you want to solve.

Please let me know if you need anything else.

**Pull request merged**
